### ISSUE TITLE
How to Get Profile Name In CWD With Bash Terminal?

### ISSUE THREAD

**Issue by MrJeevs** [gabe565/gh-profile#10]
I saw a solution to get the following with Powerlevel10k using ZSH, but is there a way to do the same for Bash?

![](https://i.gyazo.com/0f757d59697c6ae0343dd62f9a25df45.png)

**Comment by gabe565** [comment]
Yes! The `gh profile show` command will work in any prompt. So far there's only a Powerlevel10k example because that's what I use 🙂

The Bash prompt is defined by `PS1`, so I'd suggest taking a look at some customization guides like [this one on nixCraft](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html). If you post the output of `echo "$PS1"` and what you want it to look like, I could help customize it.

Only downside will be that Bash doesn't cache PS1, so adding a command to it will add some lag to the time between when a process exits and when the prompt shows up. Still, wouldn't hurt to try!

**Comment by gabe565** [comment]
@MrJeevs I'm going to close out this issue, but feel free to reopen if you have any more questions. Also, I'd gladly accept a PR if you happened to get this working!
