### ISSUE TITLE
Authentication details are not updated when switching profile

### ISSUE THREAD

**Issue by elgin9507** [gabe565/gh-profile#26]
I added 2 profiles and logged in separately to both. Having this done, authentication details stick to the profile whichever is logged in last. It seems like `gh` persists authentication details somewhere else than `~/.config/gh`. See below screenshot for the issue:

![Screenshot from 2023-04-17 12-18-10](https://user-images.githubusercontent.com/13997025/232427732-36bd61b7-9740-40ba-91da-1777115079ea.png)

You see `gh auth status` shows the same `elgin-kandasoft` even if I switch profile. The same happens when I login with `personal` profile. This time `gh auth status` gives me my personal account irrespective of `gh profile show`.

**Comment by elgin9507** [comment]
Versions of `gh` and `gh-profile`:
```
gh version 2.27.0 (2023-04-07)
https://github.com/cli/cli/releases/tag/v2.27.0
gh-profile version 1.3.2 (71a0a267052659f7ae189282a5bc56d69a4d5913)
```

**Comment by gabe565** [comment]
Hi! Thanks for reaching out.

This is happening because you logged in with the secure keyring. I'd love to add support for that, but am blocked by a limitation of the gh cli. I'm working with the gh team to get this resolved, but for the moment you'll need to login with `gh auth login --insecure-storage`.
